In [1]:
%matplotlib inline
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
import math

In [4]:
def creat_deri_matrix (size,dx):
    """
    Erstellt eine Ableitungsmatrix in beliebiger Größe
    Parameters:
    -----------
    size : größe der Matrix
    dx : Gitterabstand in x-Richtung in Metern
    dy : Gitterabstand in y-Richtung in Metern
    
    Returns:
    --------
    Ableitungsmatrix:
    np.array([[-2.,  2.,  0., ...,  0.,  0.,  0.],
              [-1.,  0.,  1., ...,  0.,  0.,  0.],
              [ 0., -1.,  0., ...,  0.,  0.,  0.],
               ..., 
              [ 0.,  0.,  0., ...,  0.,  1.,  0.],
              [ 0.,  0.,  0., ..., -1.,  0.,  1.],
              [ 0.,  0.,  0., ...,  0., -2.,  2.]]
              )
    
    """
    X = np.zeros((size,size))
    for i in range(0,size):
        for j in range (0,size):
            if (j-1) == i:
                X[i,j]=1
            if (j+1) == i:
                X[i,j]=-1

    X[0,0]=-2
    X[0,1]=2
    X[size-1,size-2]=-2
    X[size-1,size-1]=2

    X *= 1/(2*dx)
    return X

In [52]:
A = creat_deri_matrix(4,1)

In [53]:
A

array([[-1. ,  1. ,  0. ,  0. ],
       [-0.5,  0. ,  0.5,  0. ],
       [ 0. , -0.5,  0. ,  0.5],
       [ 0. ,  0. , -1. ,  1. ]])

In [55]:
A.T

array([[-1. , -0.5,  0. ,  0. ],
       [ 1. ,  0. , -0.5,  0. ],
       [ 0. ,  0.5,  0. , -1. ],
       [ 0. ,  0. ,  0.5,  1. ]])

In [45]:
a = np.arange(1,17,1).reshape(4, 4)

In [41]:
a[1,:]+=1

In [46]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
a_strich = np.dot(A,a)

In [48]:
a_strich

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [32]:
a_strich = np.dot(a,A.T)
a_strich

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])